export const ALL = 'ALL'
export const ACTIVE = 'ACTIVE'
export const COMPLETED = 'COMPLETED'

export const ACTIONS_TODO = {
    ADD_TODO: 'ADD_TODO',
    CHANGE_TEXT_TODO: 'CHANGE_TEXT_TODO',
    CHANGE_CHECK_TODO: 'CHANGE_CHECK_TODO',
    DELETE_TODO: 'DELETE_TODO',
    DELETE_COMPLETED_TODOS: 'DELETE_COMPLETED_TODOS',
    CHECK_ALL_TODOS: 'CHECK_ALL_TODOS',
    CHANGE_TYPE: 'CHANGE_TYPE',
}
