export enum FilterTypes {
  ALL = 'ALL',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum ACTIONS_TODO {
  ADD_TODO = 'ADD_TODO',

  CHANGE_TEXT_TODO = 'CHANGE_TEXT_TODO',

  CHANGE_CHECK_TODO = 'CHANGE_CHECK_TODO',

  DELETE_TODO = 'DELETE_TODO',

  CHANGE_TYPE = 'CHANGE_TYPE',

  GET_TODOS = 'GET_TODOS',

  DELETE_COMPLETED_TODOS = 'DELETE_COMPLETED_TODOS',

  CHECK_ALL_TODOS = 'CHECK_ALL_TODOS',

  TODO_FAIL = 'TODO_FAIL',
}

export enum ACTIONS_USER {
  LOG_IN = 'LOG_IN',

  REGISTRATION = 'REGISTRATION',

  GET_USER = 'GET_USER',

  LOG_OUT = 'LOG_OUT',

  SAVE_LAST_ACTION = 'SAVE_LAST_ACTION',

  CLEAR_ERROR = 'CLEAR_ERROR',

  CHECK_LOGIN = 'CHECK_LOGIN',

  RESET_PASSWORD = 'RESET_PASSWORD',
}

export enum ACTIONS_FILE {
  ADD_FILE = 'ADD_FILE',

  CHANGE_FILE = 'CHANGE_FILE',

  CHANGE_CHECK_FILE = 'CHANGE_CHECK_FILE',

  DELETE_FILE = 'DELETE_FILE',

  CHANGE_TYPE = 'CHANGE_TYPE',

  GET_FILES = 'GET_FILES',

  DELETE_COMPLETED_FILES = 'DELETE_COMPLETED_FILES',

  CHECK_ALL_FILES = 'CHECK_ALL_FILES',

  FILE_FAIL = 'FILE_FAIL',
}